### PR TITLE
Allow opening of multiple cases, each in separate tab

### PR DESCRIPTION
**Pull request by ielis**
Hi Peter, 
I think I am close to the final version of both 3S and Exomiser simulations code. I would like to be 100% sure that all the biocurated cases are correct before running the final simulations based on which we will probably assess the performance of the algorithm. 

Checking of the biocurated files was a bit painful when there are multiple cases based on a single paper so I thought it would be useful to add an option to have multiple cases opened at the same time.

Now individual cases are displayed as tabs.

Could you please take look at this and see if this is a good idea? Could you please also check if the code is working on your PC?

Thanks, Daniel

### CODE REVIEW

**Comment by pnrobinson** [comment]
THanks, Daniel, I will check this out very shortly

**Comment by pnrobinson** [comment]
I think it would be easier to split these cases into multiple separate files, actually, but I cannot seem to find one of the reviews with multiple cases to check this -- can you suggest one please?

**Comment by ielis** [comment]
[This paper](https://www.ncbi.nlm.nih.gov/pubmed/10607834) describes multiple patients with neurofibromatosis (see the Table 1).

We have curated multiple papers like this and majority of them are curated in a form that there is a single patient/case present in a JSON file. However, I think that not all the cases are in this format - there might be a JSON file with mutations identified in multiple patients and Exomiser simulations code will not be able to cope with this situation correctly and might give us erroneous results.
I was thinking that I would check the curated cases to be sure that the simulation is performed properly and the ranks are correct.

**Comment by pnrobinson** [comment]
Sorry then I do not understand -- it seems there are separate files for each patient?

**Comment by pnrobinson** [comment]
OK, let's merge this. We will disentagle the multiple patient files by hand-- better so.

**Pull request merged**
